# Generated by Django 4.2.21 on 2025-06-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='user.photos', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='user',
            name='registration_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата регистрации'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Пользователь'), (2, 'Специалист'), (3, 'Администратор')], default=1, verbose_name='кто по жизни'),
        ),
    ]
