# Generated by Django 4.2.21 on 2025-07-22 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_additionalmaterials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerschedule',
            name='day_of_week',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Пн'), (1, 'Вт'), (2, 'Ср'), (3, 'Чт'), (4, 'Пт'), (5, 'Сб'), (6, 'Вс')], verbose_name='День недели'),
        ),
    ]
