# Generated by Django 4.2.21 on 2025-07-26 04:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_workerschedule_day_of_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('bid_status', models.PositiveSmallIntegerField(choices=[(1, 'Новая'), (2, 'Потдверждена'), (3, 'Отклонена')], default=1, verbose_name='Статус заявки')),
                ('is_child_bid', models.BooleanField(default=False, verbose_name='Детская заявка')),
                ('child_sex', models.PositiveSmallIntegerField(choices=[(1, 'Мужской'), (2, 'Женский')], default=1, verbose_name='Пол ребенка')),
                ('child_borth_year', models.PositiveSmallIntegerField(verbose_name='Год рождения ребенка')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('customer', models.ForeignKey(limit_choices_to={'role': 3}, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('worker', models.ForeignKey(limit_choices_to={'role': 2}, on_delete=django.db.models.deletion.CASCADE, related_name='worker_bids', to=settings.AUTH_USER_MODEL, verbose_name='Специалист')),
            ],
        ),
    ]
