# Generated by Django 4.2.21 on 2025-07-26 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_bid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
    ]
