# Generated by Django 4.2.21 on 2025-07-26 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_bid_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bid',
        ),
    ]
