# Generated by Django 4.2.21 on 2025-07-26 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_bid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('note', models.TextField(blank=True)),
                ('customer', models.ForeignKey(limit_choices_to={'role': 3}, on_delete=django.db.models.deletion.CASCADE, related_name='customer_bids', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(limit_choices_to={'role': 2}, on_delete=django.db.models.deletion.CASCADE, related_name='worker_bids', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChildBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1)),
                ('birth_year', models.PositiveSmallIntegerField()),
                ('bid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='child_info', to='core.bid')),
            ],
        ),
    ]
