# Generated by Django 4.2.21 on 2025-07-28 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_bid_childbid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childbid',
            name='bid',
        ),
        migrations.DeleteModel(
            name='Bid',
        ),
        migrations.DeleteModel(
            name='ChildBid',
        ),
    ]
