# Generated by Django 4.2.21 on 2025-07-28 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_childbid_bid_delete_bid_delete_childbid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Новая'), (2, 'Подтверждена'), (3, 'Отклонена'), (4, 'Завершена')], default=1)),
                ('customer_note', models.TextField(blank=True)),
                ('admin_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sex', models.PositiveSmallIntegerField(choices=[(1, 'Мужской'), (2, 'Женский')], default=1)),
                ('birth_year', models.PositiveSmallIntegerField()),
                ('customer', models.ForeignKey(limit_choices_to={'role': 3}, on_delete=django.db.models.deletion.CASCADE, related_name='customer_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик')),
                ('worker', models.ForeignKey(limit_choices_to={'role': 2}, on_delete=django.db.models.deletion.CASCADE, related_name='worker_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Специалист')),
            ],
            options={
                'verbose_name': 'Заявка для ребенка',
                'verbose_name_plural': 'Заявки для детей',
            },
        ),
        migrations.CreateModel(
            name='AdultBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Новая'), (2, 'Подтверждена'), (3, 'Отклонена'), (4, 'Завершена')], default=1)),
                ('customer_note', models.TextField(blank=True)),
                ('admin_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(limit_choices_to={'role': 3}, on_delete=django.db.models.deletion.CASCADE, related_name='customer_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик')),
                ('worker', models.ForeignKey(limit_choices_to={'role': 2}, on_delete=django.db.models.deletion.CASCADE, related_name='worker_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Специалист')),
            ],
            options={
                'verbose_name': 'Заявка для взрослого',
                'verbose_name_plural': 'Заявки для взрослых',
            },
        ),
    ]
