# Generated by Django 4.2.21 on 2025-07-28 11:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_childbid_adultbid'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerschedule',
            name='pre_entry_days',
            field=models.PositiveSmallIntegerField(default=15, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(90)], verbose_name='количество дней для предварительной записи'),
        ),
        migrations.AlterField(
            model_name='adultbid',
            name='admin_note',
            field=models.TextField(blank=True, verbose_name='Администратор примечание'),
        ),
        migrations.AlterField(
            model_name='adultbid',
            name='customer_note',
            field=models.TextField(blank=True, verbose_name='Заказчик примечание'),
        ),
        migrations.AlterField(
            model_name='adultbid',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='adultbid',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Новая'), (2, 'Подтверждена'), (3, 'Отклонена'), (4, 'Завершена')], default=1, verbose_name='Статус заявки'),
        ),
        migrations.AlterField(
            model_name='adultbid',
            name='time',
            field=models.TimeField(verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='childbid',
            name='admin_note',
            field=models.TextField(blank=True, verbose_name='Администратор примечание'),
        ),
        migrations.AlterField(
            model_name='childbid',
            name='customer_note',
            field=models.TextField(blank=True, verbose_name='Заказчик примечание'),
        ),
        migrations.AlterField(
            model_name='childbid',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='childbid',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Новая'), (2, 'Подтверждена'), (3, 'Отклонена'), (4, 'Завершена')], default=1, verbose_name='Статус заявки'),
        ),
        migrations.AlterField(
            model_name='childbid',
            name='time',
            field=models.TimeField(verbose_name='Время'),
        ),
    ]
