# Generated by Django 4.2.21 on 2025-08-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_workerschedule_pre_entry_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='childbid',
            name='child_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя ребенка'),
        ),
    ]
