# Generated by Django 4.2.21 on 2025-08-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_childbid_child_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('bids_count', models.PositiveSmallIntegerField(verbose_name='Количество посещений')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Абонемент',
                'verbose_name_plural': 'Абонементы',
            },
        ),
        migrations.AlterField(
            model_name='childbid',
            name='sex',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Мужской'), (2, 'Женский')], default=1, verbose_name='Пол ребенка'),
        ),
    ]
