# Generated by Django 4.2.21 on 2025-08-01 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_abonements_alter_childbid_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='adultbid',
            name='abonement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.abonements', verbose_name='Абонемент'),
        ),
        migrations.AddField(
            model_name='childbid',
            name='abonement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.abonements', verbose_name='Абонемент'),
        ),
    ]
