# Generated by Django 4.2.21 on 2025-08-07 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_adultbid_abonement_childbid_abonement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Новая'), (2, 'Подтверждена'), (3, 'Отклонена'), (4, 'Завершена')], default=1, verbose_name='Статус заявки')),
                ('is_child_bid', models.BooleanField(default=False, verbose_name='Детская заявка')),
                ('sex', models.PositiveSmallIntegerField(choices=[(1, 'Мужской'), (2, 'Женский')], default=1, verbose_name='Пол ребенка')),
                ('child_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя ребенка')),
                ('child_age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Возраст ребенка')),
                ('customer_note', models.TextField(blank=True, verbose_name='Заказчик примечание')),
                ('admin_note', models.TextField(blank=True, verbose_name='Администратор примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('abonement', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.abonements', verbose_name='Абонемент')),
                ('customer', models.ForeignKey(limit_choices_to={'role': 3}, on_delete=django.db.models.deletion.CASCADE, related_name='customer_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик')),
                ('worker', models.ForeignKey(limit_choices_to={'role': 2}, on_delete=django.db.models.deletion.CASCADE, related_name='worker_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Специалист')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.RemoveField(
            model_name='childbid',
            name='abonement',
        ),
        migrations.RemoveField(
            model_name='childbid',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='childbid',
            name='worker',
        ),
        migrations.DeleteModel(
            name='AdultBid',
        ),
        migrations.DeleteModel(
            name='ChildBid',
        ),
    ]
