# Generated by Django 4.2.21 on 2025-08-07 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_bid_remove_childbid_abonement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='child_name',
            field=models.CharField(default='', max_length=100, verbose_name='Имя ребенка'),
        ),
    ]
