# Generated by Django 4.2.21 on 2025-08-07 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_bid_child_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='child_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя ребенка'),
        ),
    ]
