# Generated by Django 4.2.21 on 2025-08-07 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_bid_child_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='child_age',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Возраст ребенка'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='child_name',
            field=models.CharField(default='.', max_length=100, verbose_name='Имя ребенка'),
        ),
    ]
